create table if not exists public.customer_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null check (event_name in (
    'login_success',
    'service_view',
    'service_select',
    'booking_started',
    'booking_completed',
    'booking_canceled'
  )),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists customer_events_user_created_idx
  on public.customer_events (user_id, created_at desc);

create index if not exists customer_events_event_created_idx
  on public.customer_events (event_name, created_at desc);

alter table public.customer_events enable row level security;

revoke all on table public.customer_events from anon;
revoke all on table public.customer_events from authenticated;

comment on table public.customer_events is
  'Eventos operacionais mínimos do app Habitar o Corpo. Escrita e leitura somente via backend service role.';
